# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
koin = "3.5.6"
kotlin = "2.1.20"
kotlinxDatetime = "0.6.1"
kotlinxSerializationJSON = "1.7.3"
kotlinxCoroutines = "1.9.0"

ktor = "3.0.0"

exposed = "0.50.1"
logback = "1.5.6"
mysqlConnector = "8.4.0"

[libraries]
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinKtor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koinSlf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

ktorServerCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorServerCIO = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktorServerContentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorServerStatusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }

exposedCore = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposedDao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposedJdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposedKotlinxDatetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
mysqlConnector = { module = "com.mysql:mysql-connector-j", version.ref = "mysqlConnector" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
ktor = ["ktorServerCore", "ktorServerCIO", "ktorServerContentNegotiation", "ktorSerializationKotlinxJson", "ktorServerStatusPages", "koinKtor", "koinSlf4j"]
exposed = ["exposedCore", "exposedDao", "exposedJdbc", "exposedKotlinxDatetime"]
logging = ["logbackClassic"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }